version: "3" # 파일 규격 버전
services: #이 항목 밑에 실행하려는 컨테이너들을 정의
  mysql: # 서비스 명
    image: mysql/mysql-server:8.0.22 #사용할 이미지
    container_name: odd # 컨테이너 이름 설정
    ports :
      - "3306:3306" # 접근 포트 설정 ( 컨테이너 외부:컨테이너 내부)
    restart: always
    environment: # -e 옵션
      MYSQL_DATABASE: odd # 데이터 베이스 이름
      MYSQL_ROOT_HOST: '%' # MYSQL HOST
      MYSQL_ROOT_PASSWORD: "q1w2e3r4" # MYSQL 패스워드 설정 옵션
      TZ: "Asia/Seoul"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/docker/data/mysql:/var/lib/mysql # -v 옵션 (디렉토리 마운트 설정)


